//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryBusiness.DAL.Client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabSystemClient_RajLabEntities : DbContext
    {
        public LabSystemClient_RajLabEntities()
            : base("name=LabSystemClient_RajLabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Cl_AdminDetail> Tbl_Cl_AdminDetail { get; set; }
        public virtual DbSet<Tbl_Cl_ClientUser> Tbl_Cl_ClientUser { get; set; }
        public virtual DbSet<Tbl_Cl_ClientUserAttachmentDetail> Tbl_Cl_ClientUserAttachmentDetail { get; set; }
        public virtual DbSet<Tbl_Cl_ClientUserDetail> Tbl_Cl_ClientUserDetail { get; set; }
        public virtual DbSet<Tbl_Cl_ClientUserType> Tbl_Cl_ClientUserType { get; set; }
        public virtual DbSet<Tbl_Cl_ExtraWorkAttachment> Tbl_Cl_ExtraWorkAttachment { get; set; }
        public virtual DbSet<Tbl_Cl_ExtraWorkRequest> Tbl_Cl_ExtraWorkRequest { get; set; }
        public virtual DbSet<Tbl_Cl_ExtraWorkRequestStatus> Tbl_Cl_ExtraWorkRequestStatus { get; set; }
        public virtual DbSet<Tbl_Cl_ForgetPassword> Tbl_Cl_ForgetPassword { get; set; }
        public virtual DbSet<Tbl_Cl_IncorrectPasswordAttempt> Tbl_Cl_IncorrectPasswordAttempt { get; set; }
        public virtual DbSet<Tbl_Cl_Inventory> Tbl_Cl_Inventory { get; set; }
        public virtual DbSet<Tbl_Cl_InventoryRequest> Tbl_Cl_InventoryRequest { get; set; }
        public virtual DbSet<Tbl_Cl_InventoryRequestStatus> Tbl_Cl_InventoryRequestStatus { get; set; }
        public virtual DbSet<Tbl_Cl_InventoryStatusType> Tbl_Cl_InventoryStatusType { get; set; }
        public virtual DbSet<Tbl_Cl_Menu> Tbl_Cl_Menu { get; set; }
        public virtual DbSet<Tbl_Cl_MenuAssignment> Tbl_Cl_MenuAssignment { get; set; }
        public virtual DbSet<Tbl_Cl_Notification> Tbl_Cl_Notification { get; set; }
        public virtual DbSet<Tbl_Cl_OpinionRequest> Tbl_Cl_OpinionRequest { get; set; }
        public virtual DbSet<Tbl_Cl_OpinionRequestStatus> Tbl_Cl_OpinionRequestStatus { get; set; }
        public virtual DbSet<Tbl_Cl_PatientDetail> Tbl_Cl_PatientDetail { get; set; }
        public virtual DbSet<Tbl_Cl_Role> Tbl_Cl_Role { get; set; }
        public virtual DbSet<Tbl_Cl_RoleMapping> Tbl_Cl_RoleMapping { get; set; }
        public virtual DbSet<Tbl_Cl_SectionRestriction> Tbl_Cl_SectionRestriction { get; set; }
        public virtual DbSet<Tbl_Cl_Test> Tbl_Cl_Test { get; set; }
        public virtual DbSet<Tbl_Cl_TestAttachment> Tbl_Cl_TestAttachment { get; set; }
        public virtual DbSet<Tbl_Cl_TestAttachmentType> Tbl_Cl_TestAttachmentType { get; set; }
        public virtual DbSet<Tbl_Cl_TestConclusion> Tbl_Cl_TestConclusion { get; set; }
        public virtual DbSet<Tbl_Cl_TestInvestigation> Tbl_Cl_TestInvestigation { get; set; }
        public virtual DbSet<Tbl_Cl_TestReportType> Tbl_Cl_TestReportType { get; set; }
        public virtual DbSet<Tbl_Cl_TestStatus> Tbl_Cl_TestStatus { get; set; }
        public virtual DbSet<Tbl_Cl_TestSupplementReport> Tbl_Cl_TestSupplementReport { get; set; }
        public virtual DbSet<Tbl_Cl_HospitalDetail> Tbl_Cl_HospitalDetail { get; set; }
    }
}
