//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryBusiness.DAL.Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cl_Menu
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Icon { get; set; }
        public string ToolTip { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsViewable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
