//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryBusiness.DAL.Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cl_Notification
    {
        public int NotificationID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public string Type { get; set; }
        public string ClickLink { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<bool> Isviewed { get; set; }
        public Nullable<System.DateTime> ViewedDatetime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
