//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryBusiness.DAL.Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cl_LabReportConfiguration
    {
        public int ConfigID { get; set; }
        public Nullable<int> LabID { get; set; }
        public string LabName { get; set; }
        public string LabAddress { get; set; }
        public string LabCompanyNumber { get; set; }
        public string LabUniqueCode { get; set; }
        public string LabHeadOfficeAddress { get; set; }
        public string labEmail { get; set; }
        public string LabImage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string RegistrationNumber { get; set; }
        public string VatRate { get; set; }
    }
}
