//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryBusiness.DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabSystemDBEntities : DbContext
    {
        public LabSystemDBEntities()
            : base("name=LabSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Client> Tbl_Client { get; set; }
        public virtual DbSet<Tbl_ClientParameter> Tbl_ClientParameter { get; set; }
        public virtual DbSet<Tbl_Consultant> Tbl_Consultant { get; set; }
        public virtual DbSet<Tbl_ForgetPassword> Tbl_ForgetPassword { get; set; }
        public virtual DbSet<Tbl_IncorrectPasswordAttempt> Tbl_IncorrectPasswordAttempt { get; set; }
        public virtual DbSet<Tbl_Menu> Tbl_Menu { get; set; }
        public virtual DbSet<Tbl_MenuAssignment> Tbl_MenuAssignment { get; set; }
        public virtual DbSet<Tbl_Notification> Tbl_Notification { get; set; }
        public virtual DbSet<Tbl_OpinionRequest> Tbl_OpinionRequest { get; set; }
        public virtual DbSet<Tbl_OpinionRequestStatus> Tbl_OpinionRequestStatus { get; set; }
        public virtual DbSet<Tbl_Plan> Tbl_Plan { get; set; }
        public virtual DbSet<Tbl_ProviderParameterMapping> Tbl_ProviderParameterMapping { get; set; }
        public virtual DbSet<Tbl_ProviderParamter> Tbl_ProviderParamter { get; set; }
        public virtual DbSet<Tbl_Role> Tbl_Role { get; set; }
        public virtual DbSet<Tbl_RoleMapping> Tbl_RoleMapping { get; set; }
        public virtual DbSet<Tbl_SalesAndContactQuery> Tbl_SalesAndContactQuery { get; set; }
        public virtual DbSet<Tbl_SalesAndContactQueryStatus> Tbl_SalesAndContactQueryStatus { get; set; }
        public virtual DbSet<Tbl_SalesAndContactQueryType> Tbl_SalesAndContactQueryType { get; set; }
        public virtual DbSet<Tbl_SectionRestriction> Tbl_SectionRestriction { get; set; }
        public virtual DbSet<Tbl_StorageandDBProvider> Tbl_StorageandDBProvider { get; set; }
        public virtual DbSet<Tbl_SystemUser> Tbl_SystemUser { get; set; }
        public virtual DbSet<Tbl_SystemUserType> Tbl_SystemUserType { get; set; }
    }
}
