//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryBusiness.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_StorageandDBProvider
    {
        public int ProviderID { get; set; }
        public string ProviderName { get; set; }
        public string Description { get; set; }
    }
}
